require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

minimum_deployment_target = '11.0'
platform :ios, minimum_deployment_target

target 'low_version_demo_63' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'low_version_demo_63Tests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_deployment_target
      end
    end
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'low_version_demo_63-tvOS' do
  # Pods for low_version_demo_63-tvOS

  target 'low_version_demo_63-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
